server:
  port: 8084

spring:
  application:
    name: skytask-auth
  datasource:
    url: jdbc:mysql://localhost:3306/skytask?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xuliyang010318
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
  cloud:
    discovery:
      client:
        simple:
          enabled: false
    netflix:
      eureka:
        client:
          enabled: false
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: yaml
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        import-check:
          enabled: false
    sentinel:
      enabled: ${SENTINEL_ENABLED:true}
      transport:
        dashboard: ${SENTINEL_DASHBOARD:http://localhost:8858}
        port: ${SENTINEL_CLIENT_PORT:8722}
  sleuth:
    propagation:
      type: B3
    baggage:
      remote-fields: X-SkyTask-Tenant,X-SkyTask-User
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
    enabled: ${ZIPKIN_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

skytask:
  auth:
    jwt-secret: BS1/FyMut06Qwwyi5n8Rr5hdB5k5H3LVvdzEWlMv2/w=
    access-token-ttl-minutes: 60
    refresh-token-ttl-hours: 24
